### PR TITLE
Minor Fixes and DevOps Workdone

### PR DESCRIPTION
**Pull request by gvatsal60**
- Added DevContainer Support
- Minor fixes in script
- Added support for `update` alias

### CODE REVIEW

**Comment by gvatsal60** [comment]
@andmpel 
Would you mind taking a moment to review this ? I would greatly appreciate your feedback.

**Comment by andmpel** [comment]
Can you explain to me or provide so docs so I can understand what DevContainer Support is?

**Comment by gvatsal60** [comment]
DevContainer support refers to the use of Development Containers in environments like Visual Studio Code. These containers provide a standardized environment for development, making it easier to manage dependencies and ensure consistency across different setups. Here’s a breakdown of key concepts:

### What is a DevContainer?

1. **Containerization**: A DevContainer uses Docker to create an isolated environment that includes everything you need to build and run your application—like libraries, tools, and runtimes.

2. **Configuration**: A `.devcontainer` directory in your project contains configuration files (`devcontainer.json`, Dockerfile) that specify how the container is built and configured.

3. **Consistency**: By using a DevContainer, you ensure that everyone on your team has the same development environment, which minimizes "it works on my machine" issues.

### Key Components

- **Dockerfile**: Defines the environment (OS, libraries, tools) to be installed in the container.
  
- **devcontainer.json**: Configuration file that specifies settings like the Docker image, any extensions to install, and other parameters to customize the development experience.

### Benefits

- **Easy Setup**: New developers can quickly get started without manually installing software.
  
- **Portability**: The same environment can be used on different machines and platforms.

- **Isolation**: Avoids conflicts between different projects or applications running on the same machine.

### Getting Started

1. **Install Docker**: You need Docker installed on your machine.

2. **Set Up VS Code**: Install the Remote - Containers extension in Visual Studio Code.

3. **Create a DevContainer**: Add a `.devcontainer` folder to your project and create a `devcontainer.json` file to configure it.

4. **Open in Container**: Use VS Code's command palette to open the project in a container.

### Resources

- **Official Documentation**: [Visual Studio Code Dev Containers](https://code.visualstudio.com/docs/remote/devcontainer)
  
- **Docker Documentation**: [Docker Getting Started](https://docs.docker.com/get-started/)

- **Sample Projects**: Look for sample repositories on GitHub that use DevContainers to see practical examples.

This should give you a solid foundation on what DevContainer support is and how to use it! If you have specific questions or need more details on any part, feel free to ask!

**Review by andmpel — APPROVED** [review]
Really appreciate the cleanup you've done and all your help with this script @gvatsal60

**Pull request merged**
